# Generated by Django 4.0.6 on 2022-07-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('new', 'new'), ('failed', 'failed'), ('success', 'success'), ('pending', 'pending')], default='new', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('failed', 'failed'), ('success', 'success'), ('pending', 'pending')], default='new', max_length=7)),
                ('column', models.TextField()),
                ('sum', models.FloatField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='files.csv')),
            ],
        ),
    ]
