# Generated by Django 4.0.6 on 2022-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_csv_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.AddField(
            model_name='csv',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='column_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('failed', 'failed'), ('success', 'success')], default='pending', max_length=7),
        ),
    ]
